/**
 * Action Proposal Types
 * 
 * Actions are structured proposals for follow-up interactions.
 * Labels come from merchant config or LLM micro-copy generation.
 */

export type ActionType =
  | 'show_more'
  | 'refine_price'
  | 'refine_ingredient'
  | 'refine_concern'
  | 'refine_product_type'
  | 'compare'
  | 'switch_category'
  | 'ask_preferences';

export type ActionProposal = {
  id: string;
  type: ActionType;
  label: string; // Generated by ActionLabelService (merchant config or LLM)
  payload?: Record<string, unknown>; // Context-specific data (e.g., priceMaxCents for refine_price)
};

export type ActionSpec = {
  type: ActionType;
  payload?: Record<string, unknown>;
};

/**
 * Generate action specs based on query context and classification
 * Returns deterministic action specs (no labels yet)
 */
export function generateActionSpecs(
  classification: {
    type: string;
    constraints: Record<string, unknown>;
  },
  hasMoreProducts: boolean,
  shownProductCount: number
): ActionSpec[] {
  const specs: ActionSpec[] = [];

  // Always offer "show more" if there are more products
  if (hasMoreProducts || shownProductCount >= 4) {
    specs.push({
      type: 'show_more',
    });
  }

  // Offer refinement actions based on query type
  switch (classification.type) {
    case 'direct_product_search':
    case 'symptom_concern':
    case 'ingredient_exploration':
      // Offer price refinement if no price constraint
      if (!classification.constraints.priceMaxCents && !classification.constraints.priceMinCents) {
        specs.push({
          type: 'refine_price',
        });
      }

      // Offer ingredient refinement
      if (Array.isArray(classification.constraints.mustHaveIngredients) && classification.constraints.mustHaveIngredients.length > 0) {
        specs.push({
          type: 'refine_ingredient',
          payload: {
            currentIngredients: classification.constraints.mustHaveIngredients,
          },
        });
      } else {
        // Offer to add ingredient preference
        specs.push({
          type: 'ask_preferences',
          payload: {
            preferenceType: 'ingredient',
          },
        });
      }

      // Offer concern refinement for symptom_concern
      if (classification.type === 'symptom_concern') {
        if (Array.isArray(classification.constraints.concerns) && classification.constraints.concerns.length > 0) {
          specs.push({
            type: 'refine_concern',
            payload: {
              currentConcerns: classification.constraints.concerns,
            },
          });
        }
      }

      // Offer product type refinement
      if (!Array.isArray(classification.constraints.productTypes) || classification.constraints.productTypes.length === 0) {
        specs.push({
          type: 'refine_product_type',
        });
      }

      break;
    case 'gift_or_vague':
      // For vague queries, offer to refine by price or preferences
      specs.push({
        type: 'refine_price',
      });
      specs.push({
        type: 'ask_preferences',
        payload: {
          preferenceType: 'general',
        },
      });
      break;
  }

  // Limit to 3-4 actions max
  return specs.slice(0, 4);
}

/**
 * Generate unique action IDs
 */
export function generateActionId(prefix: string = 'action'): string {
  return `${prefix}-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`;
}

