/**
 * LoveShackFancy Fashion Ontology
 * 
 * Pre-computed knowledge base for LoveShackFancy fashion products.
 * This provides the vocabulary for constraint extraction and query understanding.
 */

export const LOVESHACKFANCY_ONTOLOGY = {
  // Product Collections (seasonal/theme collections)
  collections: [
    'Spring Collection',
    'Summer Collection',
    'Fall Collection',
    'Winter Collection',
    'Holiday Collection',
    'Resort Collection',
    'Bridal Collection',
    'Romantic Collection',
    'Garden Party Collection',
    'Beach Collection',
    'Vacation Collection',
    'Wedding Collection',
    'Cocktail Collection',
    'Evening Collection',
    'Daytime Collection',
    'Weekend Collection',
  ],

  // Dress/Apparel Styles
  styles: [
    'A-Line',
    'Empire Waist',
    'Fit and Flare',
    'Bodycon',
    'Shift',
    'Wrap',
    'Sheath',
    'Tiered',
    'Ruffled',
    'Tiered Ruffle',
    'Tiered Maxi',
    'Tiered Mini',
    'Puff Sleeve',
    'Balloon Sleeve',
    'Bell Sleeve',
    'Bishop Sleeve',
    'Flutter Sleeve',
    'Off-Shoulder',
    'Cold Shoulder',
    'One-Shoulder',
    'Halter',
    'Strapless',
    'V-Neck',
    'Square Neck',
    'Round Neck',
    'Boat Neck',
    'Sweetheart',
    'High Neck',
    'Mock Neck',
    'Turtleneck',
    'Cowl Neck',
    'Asymmetric',
    'Midi',
    'Maxi',
    'Mini',
    'Tea Length',
    'Knee Length',
    'Ankle Length',
    'Romantic',
    'Feminine',
    'Bohemian',
    'Vintage',
    'Classic',
    'Modern',
    'Elegant',
    'Casual',
    'Formal',
    'Cocktail',
    'Evening',
    'Daytime',
    'Beach',
    'Resort',
    'Wedding',
    'Bridal',
    'Garden Party',
    'Vacation',
  ],

  // Dress/Apparel Lengths
  lengths: [
    'Mini',
    'Knee Length',
    'Midi',
    'Tea Length',
    'Maxi',
    'Ankle Length',
    'Floor Length',
    'Above Knee',
    'Below Knee',
    'Mid-Calf',
    'Full Length',
  ],

  // Neckline Styles
  necklines: [
    'V-Neck',
    'Round Neck',
    'Square Neck',
    'Sweetheart',
    'Off-Shoulder',
    'Cold Shoulder',
    'One-Shoulder',
    'Halter',
    'Strapless',
    'Boat Neck',
    'High Neck',
    'Mock Neck',
    'Turtleneck',
    'Cowl Neck',
    'Scoop Neck',
    'Plunge',
    'Keyhole',
    'Asymmetric',
    'Bateau',
    'Jewel',
  ],

  // Sleeve Lengths
  sleeveLengths: [
    'Sleeveless',
    'Cap Sleeve',
    'Short Sleeve',
    'Three-Quarter Sleeve',
    'Long Sleeve',
    'Puff Sleeve',
    'Balloon Sleeve',
    'Bell Sleeve',
    'Bishop Sleeve',
    'Flutter Sleeve',
    'Bubble Sleeve',
    'Leg of Mutton',
    'Dolman',
    'Raglan',
    'Kimono',
  ],

  // Fabric Materials
  materials: [
    'Cotton',
    'Linen',
    'Silk',
    'Satin',
    'Chiffon',
    'Tulle',
    'Organza',
    'Taffeta',
    'Brocade',
    'Velvet',
    'Jersey',
    'Knit',
    'Wool',
    'Cashmere',
    'Polyester',
    'Rayon',
    'Viscose',
    'Modal',
    'Bamboo',
    'Tencel',
    'Lycra',
    'Spandex',
    'Elastane',
    'Denim',
    'Leather',
    'Faux Leather',
    'Suede',
    'Faux Suede',
    'Mesh',
    'Lace',
    'Embroidered',
    'Sequin',
    'Beaded',
    'Tulle',
    'Organza',
    'Chiffon',
    'Georgette',
    'Crepe',
    'Twill',
    'Poplin',
    'Voile',
    'Batiste',
    'Muslin',
  ],

  // Patterns/Prints
  patterns: [
    'Floral',
    'Abstract Floral',
    'Botanical',
    'Paisley',
    'Polka Dot',
    'Striped',
    'Plaid',
    'Gingham',
    'Check',
    'Houndstooth',
    'Herringbone',
    'Tweed',
    'Animal Print',
    'Leopard',
    'Zebra',
    'Snake',
    'Geometric',
    'Abstract',
    'Tie-Dye',
    'Ombre',
    'Gradient',
    'Solid',
    'Color Block',
    'Embroidered',
    'Applique',
    'Beaded',
    'Sequined',
    'Lace',
    'Eyelet',
    'Crochet',
    'Knit',
    'Jacquard',
    'Damask',
    'Brocade',
    'Ikat',
    'Batik',
    'Tropical',
    'Nautical',
    'Maritime',
    'Coastal',
    'Garden',
    'Romantic',
    'Vintage',
    'Retro',
    'Modern',
    'Minimalist',
    'Maximalist',
  ],

  // Occasions
  occasions: [
    'Wedding',
    'Beach Wedding',
    'Garden Wedding',
    'Outdoor Wedding',
    'Formal Wedding',
    'Bridal Shower',
    'Engagement Party',
    'Bachelorette Party',
    'Rehearsal Dinner',
    'Cocktail Party',
    'Evening Event',
    'Gala',
    'Formal Event',
    'Black Tie',
    'White Tie',
    'Date Night',
    'Anniversary',
    'Birthday',
    'Graduation',
    'Prom',
    'Homecoming',
    'Formal Dance',
    'Garden Party',
    'Tea Party',
    'Luncheon',
    'Brunch',
    'Baby Shower',
    'Bridal Shower',
    'Office',
    'Business',
    'Professional',
    'Work',
    'Casual',
    'Daytime',
    'Weekend',
    'Vacation',
    'Beach',
    'Resort',
    'Tropical',
    'Cruise',
    'Holiday',
    'Christmas',
    'New Year',
    'Easter',
    'Mother\'s Day',
    'Valentine\'s Day',
    'Spring',
    'Summer',
    'Fall',
    'Winter',
    'Everyday',
    'Special Occasion',
    'Party',
    'Celebration',
    'Festival',
    'Concert',
    'Theater',
    'Dinner',
    'Lunch',
    'Brunch',
    'Picnic',
    'Outdoor',
    'Indoor',
  ],

  // Seasons
  seasons: [
    'Spring',
    'Summer',
    'Fall',
    'Autumn',
    'Winter',
    'Year-Round',
    'All Season',
    'Transitional',
    'Resort',
    'Holiday',
  ],

  // Fit Styles
  fits: [
    'Fitted',
    'Slim Fit',
    'Skinny',
    'Regular Fit',
    'Relaxed Fit',
    'Loose Fit',
    'Oversized',
    'Boxy',
    'A-Line',
    'Empire Waist',
    'Fit and Flare',
    'Bodycon',
    'Shift',
    'Wrap',
    'Sheath',
    'Tapered',
    'Straight',
    'Wide Leg',
    'Flared',
    'Bootcut',
    'Petite',
    'Plus Size',
    'Tall',
    'Maternity',
    'Custom Fit',
  ],

  // Embellishments/Details
  embellishments: [
    'Lace',
    'Embroidery',
    'Beading',
    'Sequins',
    'Rhinestones',
    'Pearls',
    'Crystals',
    'Applique',
    'Ruffles',
    'Tiers',
    'Tiered Ruffle',
    'Pleats',
    'Gathers',
    'Smocking',
    'Tucks',
    'Darts',
    'Bow',
    'Ribbon',
    'Sash',
    'Belt',
    'Button',
    'Zipper',
    'Snap',
    'Hook and Eye',
    'Drawstring',
    'Elastic',
    'Zipper',
    'Pockets',
    'Slit',
    'Vent',
    'Cutout',
    'Keyhole',
    'Open Back',
    'Low Back',
    'High-Low',
    'Asymmetric',
    'Tiered',
    'Ruffled',
    'Flounced',
    'Pleated',
    'Gathered',
    'Draped',
    'Ruched',
    'Shirred',
    'Smocked',
    'Quilted',
    'Eyelet',
    'Crochet',
    'Fringe',
    'Tassels',
    'Pom Poms',
    'Puff Sleeve',
    'Balloon Sleeve',
    'Bell Sleeve',
    'Bishop Sleeve',
    'Flutter Sleeve',
  ],

  // Colors
  colors: [
    'White',
    'Ivory',
    'Cream',
    'Beige',
    'Nude',
    'Blush',
    'Pink',
    'Rose',
    'Rose Gold',
    'Coral',
    'Peach',
    'Salmon',
    'Red',
    'Burgundy',
    'Wine',
    'Maroon',
    'Orange',
    'Apricot',
    'Yellow',
    'Gold',
    'Mustard',
    'Lemon',
    'Green',
    'Mint',
    'Sage',
    'Olive',
    'Emerald',
    'Teal',
    'Turquoise',
    'Aqua',
    'Blue',
    'Navy',
    'Royal Blue',
    'Sky Blue',
    'Baby Blue',
    'Periwinkle',
    'Lavender',
    'Purple',
    'Violet',
    'Plum',
    'Lilac',
    'Fuchsia',
    'Magenta',
    'Black',
    'Charcoal',
    'Gray',
    'Grey',
    'Silver',
    'Taupe',
    'Brown',
    'Tan',
    'Camel',
    'Khaki',
    'Multi-Color',
    'Multi',
    'Patterned',
    'Print',
    'Floral',
    'Striped',
    'Polka Dot',
    'Plaid',
    'Gingham',
    'Abstract',
    'Tie-Dye',
    'Ombre',
    'Gradient',
  ],

  // Sizes (US Women's)
  sizes: [
    'XXS',
    'XS',
    'S',
    'M',
    'L',
    'XL',
    'XXL',
    '0',
    '00',
    '2',
    '4',
    '6',
    '8',
    '10',
    '12',
    '14',
    '16',
    '18',
    '20',
    '22',
    '24',
    '26',
    '28',
    '30',
    '32',
    'Petite',
    'Plus Size',
    'Tall',
    'Regular',
    'One Size',
    'OS',
    'OSFM',
  ],
} as const;
