/**
 * LoveShackFancy Fashion Ontology
 * 
 * Pre-computed knowledge base for LoveShackFancy fashion products.
 * This provides the vocabulary for constraint extraction and query understanding.
 */

export const LOVESHACKFANCY_ONTOLOGY = {
  // Product Collections (seasonal/theme collections)
  collections: [
    'Spring Collection',
    'Summer Collection',
    'Fall Collection',
    'Winter Collection',
    'Holiday Collection',
    'Resort Collection',
    'Bridal Collection',
    'Romantic Collection',
    'Garden Party Collection',
    'Beach Collection',
    'Vacation Collection',
    'Wedding Collection',
    'Cocktail Collection',
    'Evening Collection',
    'Daytime Collection',
    'Weekend Collection',
  ],

  // Dress/Apparel Styles
  styles: [
    'A-Line',
    'Empire Waist',
    'Fit and Flare',
    'Bodycon',
    'Shift',
    'Wrap',
    'Sheath',
    'Tiered',
    'Ruffled',
    'Tiered Ruffle',
    'Tiered Maxi',
    'Tiered Mini',
    'Puff Sleeve',
    'Balloon Sleeve',
    'Bell Sleeve',
    'Bishop Sleeve',
    'Flutter Sleeve',
    'Off-Shoulder',
    'Cold Shoulder',
    'One-Shoulder',
    'Halter',
    'Strapless',
    'V-Neck',
    'Square Neck',
    'Round Neck',
    'Boat Neck',
    'Sweetheart',
    'High Neck',
    'Mock Neck',
    'Turtleneck',
    'Cowl Neck',
    'Asymmetric',
    'Midi',
    'Maxi',
    'Mini',
    'Tea Length',
    'Knee Length',
    'Ankle Length',
    'Romantic',
    'Feminine',
    'Bohemian',
    'Vintage',
    'Classic',
    'Modern',
    'Elegant',
    'Casual',
    'Formal',
    'Cocktail',
    'Evening',
    'Daytime',
    'Beach',
    'Resort',
    'Wedding',
    'Bridal',
    'Garden Party',
    'Vacation',
  ],

  // Dress/Apparel Lengths (expanded for pants/shorts)
  lengths: [
    // Dress lengths
    'Mini',
    'Knee Length',
    'Midi',
    'Tea Length',
    'Maxi',
    'Ankle Length',
    'Floor Length',
    'Above Knee',
    'Below Knee',
    'Mid-Calf',
    'Full Length',
    
    // Pants/Jeans lengths
    'Regular',
    'Cropped',
    'Ankle',
    'Capri',
    
    // Shorts lengths
    'Short',
    '5-inch',
    '7-inch',
    '8-inch',
    '9-inch',
  ],

  // Neckline Styles
  necklines: [
    'V-Neck',
    'Round Neck',
    'Square Neck',
    'Sweetheart',
    'Off-Shoulder',
    'Cold Shoulder',
    'One-Shoulder',
    'Halter',
    'Strapless',
    'Boat Neck',
    'High Neck',
    'Mock Neck',
    'Turtleneck',
    'Cowl Neck',
    'Scoop Neck',
    'Plunge',
    'Keyhole',
    'Asymmetric',
    'Bateau',
    'Jewel',
  ],

  // Sleeve Lengths
  sleeveLengths: [
    'Sleeveless',
    'Cap Sleeve',
    'Short Sleeve',
    'Three-Quarter Sleeve',
    'Long Sleeve',
    'Puff Sleeve',
    'Balloon Sleeve',
    'Bell Sleeve',
    'Bishop Sleeve',
    'Flutter Sleeve',
    'Bubble Sleeve',
    'Leg of Mutton',
    'Dolman',
    'Raglan',
    'Kimono',
  ],

  // Fabric Materials (expanded for men's basics)
  materials: [
    'Cotton',
    'Linen',
    'Silk',
    'Satin',
    'Chiffon',
    'Tulle',
    'Organza',
    'Taffeta',
    'Brocade',
    'Velvet',
    'Jersey',
    'Knit',
    'Wool',
    'Cashmere',
    'Polyester',
    'Rayon',
    'Viscose',
    'Modal',
    'Bamboo',
    'Tencel',
    'Lycra',
    'Spandex',
    'Elastane',
    'Denim',
    'Twill',
    'Leather',
    'Faux Leather',
    'Suede',
    'Faux Suede',
    'Mesh',
    'Lace',
    'Embroidered',
    'Sequin',
    'Beaded',
    'Georgette',
    'Crepe',
    'Poplin',
    'Voile',
    'Batiste',
    'Muslin',
    'Slub',
    'Slub Jersey',
    'French Terry',
    'Fleece',
    'Nylon',
    'Canvas',
    'Chambray',
    'Corduroy',
    'Blend',
  ],

  // Patterns/Prints
  patterns: [
    'Floral',
    'Abstract Floral',
    'Botanical',
    'Paisley',
    'Polka Dot',
    'Striped',
    'Plaid',
    'Gingham',
    'Check',
    'Houndstooth',
    'Herringbone',
    'Tweed',
    'Animal Print',
    'Leopard',
    'Zebra',
    'Snake',
    'Geometric',
    'Abstract',
    'Tie-Dye',
    'Ombre',
    'Gradient',
    'Solid',
    'Color Block',
    'Embroidered',
    'Applique',
    'Beaded',
    'Sequined',
    'Lace',
    'Eyelet',
    'Crochet',
    'Knit',
    'Jacquard',
    'Damask',
    'Brocade',
    'Ikat',
    'Batik',
    'Tropical',
    'Nautical',
    'Maritime',
    'Coastal',
    'Garden',
    'Romantic',
    'Vintage',
    'Retro',
    'Modern',
    'Minimalist',
    'Maximalist',
  ],

  // Occasions (expanded for men's casual/athletic use cases)
  occasions: [
    // Formal Events
    'Wedding',
    'Beach Wedding',
    'Garden Wedding',
    'Outdoor Wedding',
    'Formal Wedding',
    'Bridal Shower',
    'Engagement Party',
    'Bachelorette Party',
    'Rehearsal Dinner',
    'Cocktail Party',
    'Evening Event',
    'Gala',
    'Formal Event',
    'Black Tie',
    'White Tie',
    
    // Social
    'Date Night',
    'Anniversary',
    'Birthday',
    'Graduation',
    'Prom',
    'Homecoming',
    'Formal Dance',
    'Garden Party',
    'Tea Party',
    'Luncheon',
    'Brunch',
    'Baby Shower',
    'Bridal Shower',
    'Party',
    'Celebration',
    'Festival',
    'Concert',
    'Theater',
    'Dinner',
    'Lunch',
    'Picnic',
    
    // Work & Professional
    'Office',
    'Business',
    'Professional',
    'Work',
    'Business Casual',
    'Smart Casual',
    
    // Casual & Everyday
    'Casual',
    'Daytime',
    'Weekend',
    'Everyday',
    'Errands',
    
    // Vacation & Travel
    'Vacation',
    'Beach',
    'Resort',
    'Tropical',
    'Cruise',
    'Travel',
    
    // Active & Sports
    'Athletic',
    'Gym',
    'Running',
    'Yoga',
    'Sports',
    'Active',
    'Workout',
    
    // Home & Relaxation
    'Lounge',
    'Lounging',
    'Sleep',
    'Sleepwear',
    'Home',
    'Relaxing',
    
    // Seasonal & Holiday
    'Holiday',
    'Christmas',
    'New Year',
    'Easter',
    'Mother\'s Day',
    'Father\'s Day',
    'Valentine\'s Day',
    'Spring',
    'Summer',
    'Fall',
    'Winter',
    
    // Settings
    'Outdoor',
    'Indoor',
    'Special Occasion',
  ],

  // Seasons
  seasons: [
    'Spring',
    'Summer',
    'Fall',
    'Autumn',
    'Winter',
    'Year-Round',
    'All Season',
    'Transitional',
    'Resort',
    'Holiday',
  ],

  // Fit Styles (expanded for men's and women's apparel)
  fits: [
    'Fitted',
    'Slim',
    'Slim Fit',
    'Skinny',
    'Regular',
    'Regular Fit',
    'Relaxed',
    'Relaxed Fit',
    'Loose Fit',
    'Oversized',
    'Boxy',
    'Athletic',
    'Athletic Fit',
    'Tailored',
    'Classic Fit',
    'Modern Fit',
    // Women's specific
    'A-Line',
    'Empire Waist',
    'Fit and Flare',
    'Bodycon',
    'Shift',
    'Wrap',
    'Sheath',
    // Pants/Jeans fits
    'Tapered',
    'Straight',
    'Straight Leg',
    'Wide Leg',
    'Flared',
    'Bootcut',
    // Size modifiers
    'Petite',
    'Plus Size',
    'Tall',
    'Maternity',
    'Custom Fit',
    'Runs Large',
    'True to Size',
  ],
  
  // Rise/Waist Placement (for jeans, pants, shorts)
  rises: [
    'Low Rise',
    'Mid Rise',
    'High Rise',
    'Natural Waist',
    'Ultra High Rise',
    'Drop Crotch',
  ],

  // Embellishments/Details
  embellishments: [
    'Lace',
    'Embroidery',
    'Beading',
    'Sequins',
    'Rhinestones',
    'Pearls',
    'Crystals',
    'Applique',
    'Ruffles',
    'Tiers',
    'Tiered Ruffle',
    'Pleats',
    'Gathers',
    'Smocking',
    'Tucks',
    'Darts',
    'Bow',
    'Ribbon',
    'Sash',
    'Belt',
    'Button',
    'Zipper',
    'Snap',
    'Hook and Eye',
    'Drawstring',
    'Elastic',
    'Zipper',
    'Pockets',
    'Slit',
    'Vent',
    'Cutout',
    'Keyhole',
    'Open Back',
    'Low Back',
    'High-Low',
    'Asymmetric',
    'Tiered',
    'Ruffled',
    'Flounced',
    'Pleated',
    'Gathered',
    'Draped',
    'Ruched',
    'Shirred',
    'Smocked',
    'Quilted',
    'Eyelet',
    'Crochet',
    'Fringe',
    'Tassels',
    'Pom Poms',
    'Puff Sleeve',
    'Balloon Sleeve',
    'Bell Sleeve',
    'Bishop Sleeve',
    'Flutter Sleeve',
  ],

  // Colors (expanded for men's neutral palette + LSF pastels)
  colors: [
    // Whites & Neutrals
    'White',
    'Ivory',
    'Cream',
    'Beige',
    'Nude',
    'Stone',
    'Sand',
    'Oatmeal',
    'Ecru',
    
    // Pinks (LSF)
    'Blush',
    'Pink',
    'Rose',
    'Rose Gold',
    'Coral',
    'Peach',
    'Salmon',
    
    // Reds
    'Red',
    'Burgundy',
    'Wine',
    'Maroon',
    'Crimson',
    
    // Oranges & Yellows
    'Orange',
    'Apricot',
    'Yellow',
    'Gold',
    'Mustard',
    'Lemon',
    
    // Greens
    'Green',
    'Mint',
    'Sage',
    'Olive',
    'Military Green',
    'Forest Green',
    'Hunter Green',
    'Emerald',
    'Teal',
    'Turquoise',
    'Aqua',
    
    // Blues
    'Blue',
    'Navy',
    'Royal Blue',
    'Sky Blue',
    'Baby Blue',
    'Periwinkle',
    'Light Blue',
    'Medium Blue',
    'Dark Blue',
    'Graphite Blue',
    'Denim Blue',
    
    // Purples
    'Lavender',
    'Purple',
    'Violet',
    'Plum',
    'Lilac',
    'Fuchsia',
    'Magenta',
    
    // Blacks & Grays
    'Black',
    'Charcoal',
    'Graphite',
    'Gray',
    'Grey',
    'Heather Gray',
    'Light Gray',
    'Dark Gray',
    'Silver',
    
    // Browns & Tans
    'Taupe',
    'Brown',
    'Tan',
    'Camel',
    'Khaki',
    'Mocha',
    'Chocolate',
    
    // Multi/Patterns
    'Multi-Color',
    'Multi',
    'Patterned',
    'Print',
    'Floral',
    'Striped',
    'Polka Dot',
    'Plaid',
    'Gingham',
    'Abstract',
    'Tie-Dye',
    'Ombre',
    'Gradient',
  ],

  // Sizes (US Women's + Men's)
  sizes: [
    // Women's letter sizes
    'XXS',
    'XS',
    'S',
    'M',
    'L',
    'XL',
    'XXL',
    'XXXL',
    
    // Women's numeric sizes
    '0',
    '00',
    '2',
    '4',
    '6',
    '8',
    '10',
    '12',
    '14',
    '16',
    '18',
    '20',
    '22',
    '24',
    '26',
    '28',
    '30',
    '32',
    
    // Men's waist sizes (waist x inseam)
    '28x28', '28x30', '28x32', '28x34',
    '29x28', '29x30', '29x32', '29x34',
    '30x28', '30x30', '30x32', '30x34',
    '31x28', '31x30', '31x32', '31x34',
    '32x28', '32x30', '32x32', '32x34',
    '33x28', '33x30', '33x32', '33x34',
    '34x28', '34x30', '34x32', '34x34',
    '35x28', '35x30', '35x32', '35x34',
    '36x28', '36x30', '36x32', '36x34',
    '38x30', '38x32', '38x34',
    '40x30', '40x32', '40x34',
    '42x32', '42x34',
    
    // Men's shorts inseam
    '28x8', '29x8', '30x8', '31x8', '32x8', '33x8', '34x8', '35x8', '36x8', '38x8', '40x8',
    
    // Size modifiers
    'Petite',
    'Plus Size',
    'Tall',
    'Regular',
    'One Size',
    'OS',
    'OSFM',
  ],

  // Age Groups (from actual dataset - must match exactly)
  // These are the canonical values found in the database
  ageGroups: [
    'Adult',
    'Kids',
    'Teen',
    'Tween',
    'Toddler',
    'Baby',
    // Combinations (comma-separated)
    'Kids, Teen',
    'Teen, Adult',
    'Kids, Teen, Adult',
    'Baby, Toddler',
    'Kids, Tween',
    'Tween, Kids',
    'Kids, Toddler',
    'Adult, Kids',
    'Adult, Teen',
    'Tween, Adult',
    // Age ranges (less common but exist in dataset)
    '0-3 months, 3-6 months, 6-12 months, 12-18 months, 18-24 months',
    '2-3 years, Toddler',
    '2-6 years, Toddler',
  ],
} as const;
